; family_position assume valores menores ou iguais a zero
; filter_by define se o critério a ser utilizado deve ser baseado no range, domain ou both
; depth deve ser um número maior que zero para que haja recomendações
; order pode ser random ou semantic (se vazio será entregue na forma como foi visitado)
; order_set pode ser class, property, all (se vazio será entregue na forma como foi visitado)
[DEFAULT]
family_position=-2
filter_by=both
depth=3
order=random
order_set=all
number_of_recommendations=5
ontology_filename=movieontology.ttl
ontology_format=ttl
